{{- if .Values.jenkinsAuthenticationEnabled }}
  {{- $apiVersion := .Values.apiVersion }}
  {{- $jenkinsAuthentication := .Values.jenkinsAuthentication}}
---
apiVersion: {{ $apiVersion }}
kind: JenkinsAuthentication
metadata:
  name: {{ $jenkinsAuthentication.name }}
  {{- with $jenkinsAuthentication.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsAuthentication.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $jenkinsAuthentication.type }}
  {{- if eq $jenkinsAuthentication.type "githubOAuth" }}
  githubOAuth:
    clientID: {{ $jenkinsAuthentication.githubOAuth.clientID }}
    {{- with $jenkinsAuthentication.githubOAuth.clientSecretRef }}
    clientSecretRef: {{- toYaml . | nindent 6 }}
    {{- end }}
    webUri: {{ $jenkinsAuthentication.githubOAuth.webUri }}
    apiUri: {{ $jenkinsAuthentication.githubOAuth.apiUri }}
    {{- with $jenkinsAuthentication.githubOAuth.scopes }}
    scopes: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- else if eq $jenkinsAuthentication.type "googleOAuth" }}
  googleOAuth:
    clientID: {{ $jenkinsAuthentication.googleOAuth.clientID }}
    {{- with $jenkinsAuthentication.googleOAuth.clientSecretRef }}
    clientSecretRef: {{- toYaml . | nindent 6 }}
    {{- end }}
    domain: {{ $jenkinsAuthentication.googleOAuth.domain }}
  {{- end }}
  {{- end }}
