apiVersion: {{ .Values.apiVersion }}
kind: JenkinsAuthentication
metadata:
  name: {{ .Values.jenkinsAuthentication.name }}
  namespace: {{ .Values.jenkinsAuthentication.namespace }}
  {{- with .Values.jenkinsAuthentication.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.jenkinsAuthentication.type }}
  {{- if eq .Values.jenkinsAuthentication.type "githubOAuth" }}
  githubOAuth:
    clientID: {{ .Values.jenkinsAuthentication.githubOAuth.clientID }}
    {{- with .Values.jenkinsAuthentication.githubOAuth.clientSecretRef }}
    clientSecretRef: {{- toYaml . | nindent 6 }}
    {{- end }}
    webUri: {{ .Values.jenkinsAuthentication.githubOAuth.webURI }}
    apiUri: {{ .Values.jenkinsAuthentication.githubOAuth.webURI }}
    {{- with .Values.jenkinsAuthentication.githubOAuth.scopes }}
    scopes: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- else if eq .Values.jenkinsAuthentication.type "googleOAuth" }}
  googleOAuth:
    clientID: {{ .Values.jenkinsAuthentication.googleOAuth.clientID }}
    {{- with .Values.jenkinsAuthentication.googleOAuth.clientSecretRef }}
    clientSecretRef: {{- toYaml . | nindent 6 }}
    {{- end }}
    domain: {{ .Values.jenkinsAuthentication.googleOAuth.domain }}
  {{- end }}