apiVersion: v2
appVersion: "0.8.2"
description: Operator Service for Jenkins
name: op-svc-jenkins
version: 0.1.1
icon: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/assets/jenkins-operator-icon.png