# Jenkins Operator Helm chart

# apiVersion is the version of the Custom Resources manifests
apiVersion: operator-service.com/v1beta1

# operator is section for configuring operator deployment
operator:
  namespace: default

  replicaCount: 1

  # image is the name (and tag) of the Jenkins Operator image
  image: operatorservice.azurecr.io/op-svc-jenkins:0.8.1

  # imagePullPolicy defines policy for pulling images
  imagePullPolicy: IfNotPresent

  # imagePullSecrets is used to pull images from private repository
  imagePullSecrets:
    - name: token

  # command
  command:
    - /manager

  # nameOverride overrides the app name
  nameOverride: ""

  # fullnameOverride overrides the deployment name
  fullnameOverride: ""

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  jenkinsNamespace: "default"
  jenkinsName: "jenkins"